/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b9c8de",
        "secondary-container": "#e89300",
        "surface-container-low": "#161d17",
        "surface-container-highest": "#2f372f",
        "on-tertiary-container": "#384658",
        "on-secondary-fixed-variant": "#663e00",
        "on-secondary-container": "#563400",
        "on-primary-fixed-variant": "#005228",
        "tertiary-container": "#a5b4ca",
        "surface-dim": "#0e150f",
        "outline": "#869486",
        "surface-bright": "#333b34",
        "on-tertiary": "#233143",
        "on-primary-fixed": "#00210c",
        "on-secondary-fixed": "#2b1700",
        "surface-container-high": "#242c25",
        "surface": "#0e150f",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#39485a",
        "secondary-fixed-dim": "#ffb961",
        "inverse-on-surface": "#2b322b",
        "surface-container": "#1a211b",
        "tertiary-fixed": "#d4e4fa",
        "on-primary-container": "#005027",
        "surface-tint": "#4ae183",
        "primary-container": "#2ecc71",
        "primary-fixed": "#6bfe9c",
        "on-surface": "#dce5da",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#4ae183",
        "inverse-surface": "#dce5da",
        "on-tertiary-fixed": "#0d1c2d",
        "on-background": "#dce5da",
        "on-surface-variant": "#bbcbbb",
        "tertiary": "#c0d0e6",
        "error-container": "#93000a",
        "secondary": "#ffb961",
        "secondary-fixed": "#ffddb9",
        "on-primary": "#003919",
        "on-secondary": "#472a00",
        "on-error": "#690005",
        "outline-variant": "#3d4a3e",
        "surface-container-lowest": "#09100a",
        "inverse-primary": "#006d37",
        "primary": "#54e98a",
        "surface-variant": "#2f372f",
        "background": "#0e150f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-padding": "20px",
        "unit-base": "4px",
        "gutter-md": "16px",
        "sidebar-width": "260px",
        "container-gap": "24px"
      }
    },
  },
  plugins: [],
}
